version: '3.8'

services:
  myrestapi-1:
    build:
      context: .
      dockerfile: Dockerfile
  myrestapi-2:
    build:
      context: .
      dockerfile: Dockerfile
  myrestapi-3:
    build:
      context: .
      dockerfile: Dockerfile
  balancer:
    image: nginx:alpine3.21
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/templates
